# Utiliser une image de base Python
FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers de configuration
COPY mqtt/requirements.txt /app/

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source FastAPI
COPY mqtt /app/

# Exposer le port pour FastAPI
EXPOSE 8001

# Commande par défaut pour démarrer le serveur FastAPI
CMD ["uvicorn", "main_app:app", "--host", "0.0.0.0", "--port", "8001"]
